version: '3.4'

services:
  apione:
    container_name: apione
    build:
      context: ./ApiOne
      dockerfile: Dockerfile
    ports:
        - "0.0.0.0:8088:80"
    networks:
      - meta-network

  apitwo:
    container_name: apitwo
    build:
      context: ./ApiTwo
      dockerfile: Dockerfile
    ports:
        - "0.0.0.0:8089:80"
    depends_on:
      - apione
    networks:
      - meta-network
    links:
      - apione
networks:
  meta-network:
    driver: bridge
